# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQEnLsbVEnrVMzANK509bU21ZMssvkhf
"""

import pandas as pd

df = pd.read_csv('data.csv', encoding='unicode_escape')

df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]

df['Revenue'] = df['Quantity'] * df['UnitPrice']

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df.to_csv('cleaned_ecommerce_data.csv', index=False)

print("Data cleaned and saved successfully!")